# Models for supervisor agent, load_preference_agent, and web_search_agent
# And Search Tools 

llm_models:
  - supervisor_models: gpt-4.1-mini-2025-04-14, gpt-4.1-2025-04-14, gpt-5-2025-08-07, o3-2025-04-16, o4-mini-2025-04-16
    type: openai
    subagent_model: gpt-4.1-mini-2025-04-14   
  - supervisor_models: gemini-2.5-flash, gemini-2.5-pro
    type: google
    subagent_model: gemini-2.5-flash
  - supervisor_models: claude-3-5-haiku-20241022, claude-3-5-sonnet-20241022, claude-3-7-sonnet-20250219, claude-sonnet-4-20250514, claude-opus-4-20250514
    type: anthropic
    subagent_model: claude-3-5-haiku-20241022

embedding_models:
  - models: text-embedding-3-small, text-embedding-3-large, text-embedding-ada-002
    type: openai
  - models: text-embedding-004, gemini-embedding-exp-03-07
    type: google
  - models: voyage-3.5-lite, voyage-3.5, voyage-3.5-large, voyage-code-3, voyage-finance-2, voyage-law-2
    type: anthropic

search_tools:
  - current_search_tool_name: tavily_search
    search_tool_names: tavily_search, google_search

current_models:
  llm_service_type: supervisor_agent
  supervisor_llm_model: gpt-4.1-mini-2025-04-14
  subagent_llm_model: gpt-4.1-mini-2025-04-14
  subagent_names: web_search_agent, load_preference_agent
  search_tool_name: tavily_search
  embedding_model: text-embedding-3-small
  embedding_type: openai