# API Pricing
openai: # Standard Text tokens Pricing, 1백만 토큰당 가격 (USD)
  - name: gpt-5-2025-08-07
    input_price: 1.25
    cached_input_price: 0.125
    output_price: 10.00
  - name: gpt-5-mini-2025-08-07
    input_price: 0.25
    cached_input_price: 0.025
    output_price: 2.00
  - name: gpt-5-chat-latest
    input_price: 1.25
    cached_input_price: 0.125
    output_price: 10.00
  - name: gpt-4.1-2025-04-14
    input_price: 2.00
    cached_input_price: 0.50
    output_price: 8.00
  - name: gpt-4.1-mini-2025-04-14
    input_price: 0.40
    cached_input_price: 0.10
    output_price: 1.60
  - name: gpt-4o-latest
    input_price: 2.50
    cached_input_price: 1.25
    output_price: 10.00
  - name: gpt-4o-mini-2024-07-18
    input_price: 0.15
    cached_input_price: 0.075
    output_price: 0.60
  - name: o3-2025-04-16
    input_price: 2.00
    cached_input_price: 0.50
    output_price: 8.00
  - name: o3-pro-2025-06-10
    input_price: 20.00
    cached_input_price: null
    output_price: 80.00
  - name: o3-deep-research-2025-06-26
    input_price: 10.00
    cached_input_price: 2.50
    output_price: 40.00
  - name: o4-mini-2025-04-16
    input_price: 1.10
    cached_input_price: 0.28
    output_price: 4.40
  - name: o4-mini-deep-research-2025-06-26
    input_price: 2.00
    cached_input_price: 0.50
    output_price: 8.00

google: # 유료 등급, 1백만 토큰당 가격 (USD)
  - name: gemini-2.5-pro
    input_price: 1.25
    output_price: 10.00
    cached_input_price: 0.31
    cache_read_price: null
    batch_input_price: null
    batch_output_price: null
    tier_value: 200000 #tokens
    tiered_pricing:
      - tier: "<=200k_tokens"
        input_price: 1.25
        output_price: 10.00
        cached_input_price: 0.31
        cache_read_price: null
      - tier: ">200k_tokens"
        input_price: 2.50
        output_price: 15.00
        cached_input_price: 0.625
        cache_read_price: null
    storage_price_per_hour: 4.50
    google_search_grounding:
      free_capacity_rpd: 1500
      request_unit: 1000
      price: 35
    live_api: null

  - name: gemini-2.5-flash
    input_price: 0.30
    output_price: 2.50
    cached_input_price: 0.075
    cache_read_price: null
    batch_input_price: null
    batch_output_price: null
    tiered_pricing: null
    input_types:
      - type: text
        price: 0.30
      - type: image
        price: 0.30
      - type: video
        price: 0.30
      - type: audio
        price: 1.00
    cached_input_types:
      - type: text
        price: 0.075
      - type: image
        price: 0.075
      - type: video
        price: 0.075
      - type: audio
        price: 0.25
    storage_price_per_hour: 1.00
    google_search_grounding:
      free_capacity_rpd: 1500
      request_unit: 1000
      price: 35
    live_api:
      - type: text
        input_price: 0.50
        output_price: 2.00
      - type: image
        input_price: 3.00
        output_price: null
      - type: video
        input_price: 3.00
        output_price: null
      - type: audio
        input_price: 3.00
        output_price: 12.00

anthropic: # USD per 1M Tokens
  - name: claude-opus-4.1-20250805
    input_price: 15.00
    cached_input_price: 
      - unit: 5 #min
        price: 18.75
      - unit: 60 #min
        price: 30.00
    output_price: 75
    cache_read_price: 1.50
    batch_input_price: 7.50
    batch_output_price: 37.50
  - name: claude-opus-4-20250514
    input_price: 15
    cached_input_price:
      - unit: 5 #min
        price: 18.75
      - unit: 60 #min
        price: 30.00
    output_price: 75.00
    cache_read_price: 1.50
    batch_input_price: 7.50
    batch_output_price: 37.50
  - name: claude-sonnet-4-20250514
    input_price: 3
    cached_input_price: 
      - unit: 5 #min
        price: 3.75
      - unit: 60 #min
        price: 6
    output_price: 15
    cache_read_price: 0.30
    batch_input_price: 1.50
    batch_output_price: 7.50
    tier_value: 200000 #tokens
    tiered_pricing:
      - tier: "<=200k_tokens"
        input_price: 3.00
        output_price: 15.00
        cached_input_price: 3.75
        cache_read_price: 0.30
      - tier: ">200k_tokens"
        input_price: 6.00
        output_price: 22.50
        cached_input_price: 7.50
        cache_read_price: 0.60
  - name: claude-sonnet-3.7-20250219
    input_price: 3
    cached_input_price:  
      - unit: 5 #min
        price: 3.75
      - unit: 60 #min
        price: 6.00
    output_price: 15.00
    cache_read_price: 0.30
    batch_input_price: 1.50
    batch_output_price: 7.50
  - name: claude-sonnet-3.5-20241022
    input_price: 3.00
    cached_input_price:  
      - unit: 5 #min
        price: 3.75
      - unit: 60 #min
        price: 6.00
    output_price: 15.00
    cache_read_price: 0.30
    batch_input_price: 1.50
    batch_output_price: 7.50
  - name: claude-haiku-3.5-20241022
    input_price: 0.80
    cached_input_price:  
      - unit: 5 #min
        price: 1.00
      - unit: 60 #min
        price: 1.60
    output_price: 4.00
    cache_read_price: 0.08
    batch_input_price: 0.40
    batch_output_price: 2.00


