# models.yaml
llm_models:
  - name: gpt-4.1-mini-2025-04-14
    type: openai
    model_name: gpt-4.1-mini-2025-04-14
    temperature: 0.7
    max_tokens: 4096
  - name: gpt-4.1-2025-04-14
    type: openai
    model_name: gpt-4.1-2025-04-14
    temperature: 0.7
    max_tokens: 4096
  - name: gpt-5-2025-08-07
    type: openai
    model_name: gpt-5-2025-08-07
    temperature: 0.7
    max_tokens: 4096 
  - name: o3-2025-04-16
    type: openai
    model_name: o3-2025-04-16
    temperature: 0
    max_tokens: 4096
  - name: o4-mini-2025-04-16
    type: openai
    model_name: o4-mini-2025-04-16
    temperature: 0
    max_tokens: 4096
  - name: gemini-2.5-flash
    type: google
    model_name: gemini-2.5-flash
    temperature: 0.8
    max_tokens: 4096
  - name: gemini-2.5
    type: google
    model_name: gemini-2.5
    temperature: 0.8
  - name: gemini-2.0-flash
    type: google
    model_name: gemini-2.0-flash
    temperature: 0.8
    max_tokens: 4096
  - name: claude-sonnet-4-20250514
    type: anthropic
    model_name: claude-sonnet-4-20250514
    temperature: 0.8
    max_tokens: 4096
  - name: claude-3-7-sonnet-20250219
    type: anthropic
    model_name: claude-3-7-sonnet-20250219
    temperature: 0.8
    max_tokens: 4096
  - name: claude-3-5-sonnet-20241022
    type: anthropic
    model_name: claude-3-5-sonnet-20241022
    temperature: 0.8
    max_tokens: 4096
  - name: claude-3-5-haiku-20241022
    type: anthropic
    model_name: claude-3-5-haiku-20241022
    temperature: 0.8
    max_tokens: 4096
  - name: claude-opus-4-20250514
    type: anthropic
    model_name: claude-opus-4-20250514
    temperature: 0.8
    max_tokens: 4096  
  - name: huggingface_llama2
    type: huggingface
    model_name: meta-llama/Llama-2-7b-chat-hf
    api_key: your_huggingface_api_key_here # Hugging Face API (inference endpoint)
    # 추가적인 Hugging Face 모델 관련 설정 (예: endpoint URL)